---
include:
  - board: corne_right
    shield: nice_epaper
    artifact-name: corne_right
  - board: corne_left
    shield: nice_epaper
    artifact-name: corne_left
  - board: corne_left
    shield: nice_epaper
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: corne_studio_left
